CREATE VIEW `compares_full_view` AS
SELECT DISTINCT T.ID AS TEST_ID, T.NAME AS TEST_NAME, /*T.TITLE_MARK1 AS TEST_TITLE_MARK1, T.TITLE_MARK2 AS TEST_TITLE_MARK2,*/
CONCAT(TF1.FILE_NAME, '.', TF1.EXTENSION) AS TEST_FILE1, CONCAT(TF2.FILE_NAME, '.', TF2.EXTENSION) AS TEST_FILE2, 
S1.NAME AS SOURCE1_NAME, S2.NAME AS SOURCE2_NAME,
TIT.POSITION_SOURCE1, TIT.POSITION_SOURCE2, TIT.TITLE
FROM COMPARES.TEST T
JOIN COMPARES.REL_TEST_PAR RTP ON T.ID = RTP.TEST_ID
JOIN COMPARES.REL_PAR_TITLE RPT ON RTP.PAR_ID = RPT.PAR_ID
JOIN COMPARES.SOURCE S1 ON S1.ID = T.SOURCE1_ID
JOIN COMPARES.SOURCE S2 ON S2.ID = T.SOURCE2_ID
JOIN COMPARES.PAR P ON P.ID = RTP.PAR_ID
JOIN COMPARES.TEST_FILE TF1 ON TF1.ID = P.TEST_FILE_SOURCE1
JOIN COMPARES.TEST_FILE TF2 ON TF2.ID = P.TEST_FILE_SOURCE2
JOIN COMPARES.TITLE TIT ON TIT.ID = RPT.TITLE_ID;